# Generated by Django 4.1.2 on 2023-11-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('VCU', 'VCU'), ('DIAG', 'DIAG'), ('TCN', 'TCN'), ('ETH', 'ETH'), ('CANNODE', 'CANNODE')], default='VCU', max_length=20)),
                ('verze', models.IntegerField(max_length=5)),
                ('poznamka', models.TextField(max_length=200)),
            ],
        ),
    ]
