# Generated by Django 4.1.2 on 2023-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karty',
            name='cislo',
            field=models.IntegerField(default=0, max_length=40),
        ),
    ]
