# Generated by Django 4.1.2 on 2023-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_karty_cislo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polozky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Box', 'Box'), ('Příslušenství', 'Příslušenství'), ('Ostatní', 'Ostatní')], default='Box', max_length=30)),
                ('nazev', models.TextField(max_length=100)),
                ('poznamka', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Karty',
        ),
    ]
